# Generated by Django 5.0.5 on 2024-05-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('cover_photo', models.CharField(max_length=9999)),
                ('profile_photo', models.CharField(max_length=9999)),
                ('about', models.CharField(max_length=9999)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
