# Generated by Django 5.0.5 on 2024-05-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('percentage', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('start_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
