# Generated by Django 5.0.5 on 2024-05-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='start_date',
            field=models.DateField(),
        ),
    ]
