# Generated by Django 5.0.5 on 2024-05-08 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
        ('job_offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employers.employer'),
        ),
    ]
