# Generated by Django 5.0.5 on 2024-05-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0002_joboffer_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.CharField(max_length=9999),
        ),
    ]
