# Generated by Django 5.0.5 on 2024-05-08 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0002_alter_joboffer_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
