# Generated by Django 5.0.4 on 2024-05-06 20:39

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffers',
            name='created_on',
            field=models.DateField(default=datetime.date(2024, 5, 6)),
        ),
        migrations.AddField(
            model_name='joboffers',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffers',
            name='due_date',
            field=models.DateField(default=datetime.date(2024, 5, 6)),
            preserve_default=False,
        ),
    ]
