# Generated by Django 5.0.4 on 2024-05-06 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0002_joboffers_created_on_joboffers_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffers',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
