# Generated by Django 5.0.4 on 2024-05-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0003_alter_joboffers_created_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobOffers',
            new_name='JobOffer',
        ),
    ]
