# Generated by Django 5.0.5 on 2024-05-14 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_remove_application_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sent_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
