# Generated by Django 5.0.5 on 2024-05-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0003_application_sent_date_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrecommendation',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
