# Generated by Django 5.0.5 on 2024-05-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='profile_image',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
