# Generated by Django 5.0.5 on 2024-05-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='image',
            new_name='profile_image',
        ),
    ]
