# Generated by Django 5.0.5 on 2024-05-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_image_jobseekerprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='full_name',
            field=models.CharField(default='PlaceholderName', max_length=100),
            preserve_default=False,
        ),
    ]
